[package]
name = "aliyundrive-cli"
version = "0.1.0"
edition = "2021"

[package.metadata.winres]
LegalCopyright = "Copyright © 2022"
# this FileDescription overrides package.description
FileDescription = "aliyundrive-cli"
email = "verticle@foxmail.com"
authors = "gngpp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#reqwest = { version = "0.11", features = ["blocking", "json"] }
#openssl = { version = "0.10", features = ["vendored"] }
anyhow = "1.0"
log = "0.4.0"
env_logger = "0.8.4"
clap = { version = "3.1.18", features = ["cargo"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.24"
lazy_static = "1.4.0"
chrono = "0.4.9"
tokio = { version = "1", features = ["full"] }

qrcode = { path = "src/qrcode" }
drive = { path = "src/drive" }

[workspace]
members = [
    "src/qrcode",
    "src/drive",
]

